---
title: "Data Manipulation"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)

```

## Import data

I want to import 'FAS_litters.csv'

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## `select`

Let's select some columns.

```{r}
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight:gd_of_birth) # select several coloumn
select(litters_df,-litter_number) # not select one column
select(litters_df, group, starts_with("pups")) # select column start with ""
select(litters_df, GROUP = group, litter_number) # rename column
rename(litters_df, GROUP = group)
select(litters_df, litter_number, everything()) # change column order
relocate(litters_df, litter_number) # same as above
select(pups_df, litter_number, sex, pd_ears) # learning ass
```

##`filter`

Let's get rid of rows

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7")
filter(litters_df, gd0_weight < 23)
filter(litters_df, pups_survive != 4)  #!(pups_survive == 4)
filter(litters_df, group %in% c("Con7", "Con8"))  # either 7 or 8
filter(litters_df, group == "Con7", gd_of_birth == 20) # both condition satisfy

drop_na(litters_df) # will remove any row with a missing value
drop_na(litters_df, gd0_weight) # will remove rows for which gd0_weight is missing.
```

##`mutate`

let's add or change columns

```{r}
mutate(
  litters_df,
  weight_change = gd18_weight - gd0_weight,
  group = str_to_lower(group) # lower case
)
```

## `arrange`

Let's rearrange the data

```{r}
arrange(litters_df, gd_of_birth, gd0_weight)
```
}

## Pipes

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_select = select(litters_data_clean_names, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")
#too long!
#do this
litters_df = 
  read_csv("data/FAS_litters.csv") %>% #command+shift+m
  janitor::clean_names() %>% 
  select(group, pups_survive) %>% 
  filter(group == "Con7")

litters_df = 
  read_csv("data/FAS_litters.csv") %>% #command+shift+m
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change) %>% 
  filter(group %in% c("con7","con8")) %>% #need to use lower case
  select(litter_number, group, weight_change, everything())

```


```{r}
litters_data_clean = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )

litters_data_clean
```
}


